name = "little-lantern-website"
account_id = "5965dcfa5a63c18e2c1c816ac52ce52e"
workers_dev = false

routes = [
  { pattern = "littlelantern.in", custom_domain = true }
]

[build]
command = "npm run build"
upload.format = "service-worker"

[site]
bucket = "./build"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200