name = "worker-script"
type = "javascript"
account_id = "5965dcfa5a63c18e2c1c816ac52ce52e"
workers_dev = true

routes = [
  { pattern = "littlelantern.in/*", custom_domain = true }
]

[build]
command = "npm run build"
upload.format = "service-worker"