name = "little-lantern-website"
account_id = "5965dcfa5a63c18e2c1c816ac52ce52e"
workers_dev = false

[site]
bucket = "./build"

[build]
command = "npm run build"
upload.format = "modules"

main = "./build/index.js"  # Fix this path if necessary

[[redirects]]
from = "/*"
to = "/index.html"
status = 200