name = "worker-script"
type = "javascript"
account_id = "your-account-id"
workers_dev = true

routes = [
  { pattern = "littlelantern.in/*", custom_domain = true }
]

[build]
command = "npm run build"
upload.format = "service-worker"