name = "little-lantern-website"
account_id = "5965dcfa5a63c18e2c1c816ac52ce52e"
workers_dev = false

routes = [
  { pattern = "littlelantern.in", custom_domain = true }
]

[site]
bucket = "./build"  # Ensure this points to your React build output

[build]
command = "npm run build"
upload.format = "modules"  # Service worker is not needed for static sites

[[redirects]]
from = "/*"
to = "/index.html"
status = 200